import type { ErrorScenario } from '../registry'

export const validationScenarios: ErrorScenario[] = [
  {
    id: 'validation.no-segments',
    label: 'Bundle has no segments',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Bundle has no segments' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.deadline-passed',
    label: 'Bundle deadline has passed',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Bundle deadline has passed' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.malformed-ids-amounts',
    label: 'Malformed idsAndAmounts entry',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Malformed idsAndAmounts entry' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.duplicate-chain-ids',
    label: 'Duplicate chain ids in segments',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Duplicate chain ids in segments' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.different-target-chains',
    label: 'Segments have different target chains',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Segments have different target chains' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.deposit-id-mismatch',
    label: 'Segment depositId mismatch',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Segment depositId mismatch' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.segment-deadline-passed',
    label: 'Segment deadline has passed',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Segment deadline has passed' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.segment-deadline-after-bundle',
    label: 'Segment deadline after bundle deadline',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Segment deadline after bundle deadline' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.segment-deadline-too-close',
    label: 'Segment deadline too close to bundle deadline',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Segment deadline too close to bundle deadline' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.different-fill-deadlines',
    label: 'Different fill deadlines',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Different fill deadlines' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.incorrect-arbiter',
    label: 'Incorrect arbiter address',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Incorrect arbiter address' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.invalid-notarized-actions',
    label: 'Invalid notarized actions',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Invalid notarized actions' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.samechain-not-notarized',
    label: 'Same-chain not notarized',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Same-chain not notarized' }], traceId: 'mock-trace-000' },
  },
  {
    id: 'validation.invalid-event-type',
    label: 'Invalid event type',
    category: 'validation',
    statusCode: 400,
    endpoints: ['intent_store'],
    response: { errors: [{ message: 'Invalid event type' }], traceId: 'mock-trace-000' },
  },
]
